# Generated by Django 2.2.6 on 2019-10-20 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_management_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersystem',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='usersystem',
            name='password',
        ),
        migrations.AlterField(
            model_name='usersystem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
