# Generated by Django 2.2.6 on 2019-10-21 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_management_system', '0003_auto_20191020_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersystem',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='usersystem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='UserSystem',
        ),
    ]
