# Generated by Django 2.2.6 on 2019-10-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_management_system', '0009_auto_20191022_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
